<a href="https://colab.research.google.com/github/KaosElegent/tensorflow-fun/blob/main/collab/TensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
scalar = tf.constant(7)
print(scalar)
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


In [3]:
vector = tf.constant([10,10])
print(vector)
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [4]:
matrix = tf.constant([
    [10,11],
    [12,13]
])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10 11]
 [12 13]], shape=(2, 2), dtype=int32)
2


Matrix with a custom datatype

In [5]:
matrix = tf.constant([
    [10,11],
    [12,13]
],dtype='float32')
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10. 11.]
 [12. 13.]], shape=(2, 2), dtype=float32)
2


In [6]:
tensor = tf.constant([
    [
      [1,2,3]
    ],
    [
      [4,5,6],
    ],
    [
      [7,8,9]
    ]

])
print(tensor)
print(tensor.ndim)
print(tensor.shape)

tf.Tensor(
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]], shape=(3, 1, 3), dtype=int32)
3
(3, 1, 3)


Generating Tensors

In [7]:
seed = tf.random.Generator.from_seed(42) #creating a generator object

In [8]:
normal_distribution_tensor = seed.normal(shape=(3,2))
uniform_distribution_tensor = seed.uniform(shape=(3,2))
print(normal_distribution_tensor) #normal distribution of random numbers
print(uniform_distribution_tensor) #uniform distribution of random numbers

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.7647915  0.03845465]
 [0.8506975  0.20781887]
 [0.711869   0.8843919 ]], shape=(3, 2), dtype=float32)


In [9]:
# tensors of xeros or ones are usually used as a starting point
zeros = tf.zeros(shape=(3,2))
ones = tf.ones(shape=(3,2))

print(zeros)
print(ones)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [10]:
import numpy as np

In [11]:
numpy_arr = np.arange(1,25,dtype=np.int32)
print(numpy_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [12]:
numpy_tensor = tf.constant(numpy_arr,shape=[2,4,3])
print(numpy_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]], shape=(2, 4, 3), dtype=int32)


Operations on Tensors


In [13]:
rank4_tensor = tf.zeros([2,3,4,5])
print(rank4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [14]:
print("Size: ", tf.size(rank4_tensor))
print("Shape: ", rank4_tensor.shape)
print("Dimension: ", rank4_tensor.ndim)

Size:  tf.Tensor(120, shape=(), dtype=int32)
Shape:  (2, 3, 4, 5)
Dimension:  4


In [15]:
basic_tensor = tf.constant([
    [10,11],
    [12,13]
])
print(basic_tensor)

tf.Tensor(
[[10 11]
 [12 13]], shape=(2, 2), dtype=int32)


In [16]:
print(basic_tensor + 10)
print(basic_tensor - 10)
print(basic_tensor * 10)
print(basic_tensor / 10)

tf.Tensor(
[[20 21]
 [22 23]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 110]
 [120 130]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  1.1]
 [1.2 1.3]], shape=(2, 2), dtype=float64)


Matrix Multiplication

https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [22]:
# row, columns
# 2,3 * 3,2 will give a matrix of 2,2
matrix_1 = tf.constant([
    [1,2,3],
    [4,5,6]
])

matrix_2 = tf.constant([
    [7,8],
    [9,10],
    [11,12]
])

print(matrix_1)
print(matrix_2)
print(tf.matmul(matrix_1,matrix_2))


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


Reshaping & Transposing


In [21]:
print(tf.reshape(matrix_1,[6]))
print(tf.reshape(matrix_1,[6,1]))

print(tf.transpose(matrix_1))

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]], shape=(6, 1), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


Aggregate Operations

In [28]:
tensor = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype='float32')

print(tf.reduce_min(tensor))
print(tf.reduce_max(tensor))
print(tf.reduce_sum(tensor))

tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(45.0, shape=(), dtype=float32)


Standard Deviation & Variance

[x,y,z]

mean = (x+y+z)/3

variance = [ (x-mean)^2 + (y-mean)^2 + (z-mean)^2 ] / 3

standard deviation = root(variance)

In [29]:
print(tf.math.reduce_std(tensor))
print(tf.math.reduce_variance(tensor))

tf.Tensor(2.5819888, shape=(), dtype=float32)
tf.Tensor(6.6666665, shape=(), dtype=float32)


extra operations


In [30]:
print(tf.sqrt(tensor))
print(tf.square(tensor))
print(tf.math.log(tensor))

tf.Tensor(
[[1.        1.4142135 1.7320508]
 [2.        2.236068  2.4494898]
 [2.6457512 2.828427  3.       ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.        0.6931472 1.0986123]
 [1.3862944 1.609438  1.7917595]
 [1.9459102 2.0794415 2.1972246]], shape=(3, 3), dtype=float32)
